repos:
  # General pre-commit checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  # ruff - formatting and linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.8"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
      - id: ruff-format

  # Disabled until project is ready for it
  # # mypy - static type checking
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v1.10.0"
  #   hooks:
  #     - id: mypy
  #       files: src
  #       args: []

  # codespell - spellchecking
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.3.0"
    hooks:
      - id: codespell
        args: ["--ignore-words-list", "Commun,CCompiler"]

  # shellcheck - shell script checker
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: "v0.10.0.1"
    hooks:
      - id: shellcheck
