name: pipic_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - numba
  - llvmlite
  - pytest
  - pip:
      - --index-url https://test.pypi.org/simple/
      - --extra-index-url https://pypi.org/simple
      - pipic==1.3rc10
