# Build the package and publish it to PyPI after tests pass.
name: CD

on:
  push:
    tags:
      - "v*"

env:
  FORCE_COLOR: 3

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y libfftw3-dev

      - name: Checkout the project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This is needed in order to fetch version tags from git

      - name: Build package
        run: pipx run build

      - name: Upload dist/ as artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/*

  deploy:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
#    environment:
#      name: pypi
#      url: https://pypi.org/p/pipic/
#    permissions:
#      id-token: write
    needs: [dist]

    steps:
      - name: Download dist/ artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

#      - name: Publish package distributions to PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Publish package distributions to TestPyPI
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          repository-url: https://test.pypi.org/legacy/
#          verbose: true
#          print-hash: true
        run: echo "Publish here!"
